"""add_user_role

Revision ID: 7704f577cb5a
Revises: 99af16a3787b
Create Date: 2024-10-18 09:19:36.340379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7704f577cb5a'
down_revision: Union[str, None] = '99af16a3787b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.add_column('users', sa.Column('user_role', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'role', ['user_role'], ['role_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'user_role')
    op.drop_table('role')
    # ### end Alembic commands ###
