"""add_signup

Revision ID: c3110ade20c8
Revises: 881e2c01090b
Create Date: 2024-10-24 21:37:29.176590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3110ade20c8'
down_revision: Union[str, None] = '881e2c01090b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('surname', sa.String(length=30), nullable=True),
    sa.Column('firstname', sa.String(length=30), nullable=False),
    sa.Column('middlename', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('confirm_code_hash', sa.String(length=128), nullable=True),
    sa.Column('confirm_code_expired', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidates')
    # ### end Alembic commands ###
