"""add_candidates

Revision ID: ec38fce9205d
Revises: 7704f577cb5a
Create Date: 2024-10-25 08:51:25.750830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec38fce9205d'
down_revision: Union[str, None] = '7704f577cb5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('surname', sa.String(length=30), nullable=True),
    sa.Column('firstname', sa.String(length=30), nullable=False),
    sa.Column('middlename', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('confirm_code_hash', sa.String(length=128), nullable=True),
    sa.Column('confirm_code_expired', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidates')
    # ### end Alembic commands ###
